### ISSUE TITLE
Wrong media types in quiz editor 

### ISSUE THREAD

**Issue by fosterfarrell9** [MaMpf-HD/mampf#496]
The search form in the quiz editor which is used for selection of questions/remarks in a quiz now has an "all" media button. When this is selected, media of all types (not only questions and reamrks) are searched, but hovering over the results (of wrong type) then results in an exception:

```
 undefined method `locale_with_inheritance' for nil:NilClass I18n.locale = @quizzable.locale_with_inheritance 

/usr/src/app/app/controllers/media_controller.rb:488:in `fill_quizzable_preview'
```
The "all" button should be removed in this form, and exception handling should be improved.

**Comment by fosterfarrell9** [comment]
Also, searching Questions as a non-admin editor or teacher will not give any results; and in the media search in the admin area, you cannot even select "questions as type. These are all regressions introduced in #420.

**Comment by fosterfarrell9** [comment]
Yes, this can be closed via #506.
